browser=chrome
CPBaseUrl=https://www.nba.com/warriors
FilePath=target/jacket-details.txt
DP1BaseUrl=https://www.nba.com/sixers/
DP2BaseUrl=https://www.nba.com/bulls/
FirefoxDriverPath_Win=NBA-Automation/automation-framwework/src/test/resources//geckodriver.exe
FirefoxDriverPath_Mac=NBA-Automation/automation-framwework/src/test/resources/geckodriver
api_url=https://cdn.nba.com/static/json/liveData/boxscore/boxscore_0012500008.json